### ISSUE TITLE
Unable to import via Gradle 

### ISSUE THREAD

**Issue by troyjperales** [MeetMe/font-compat#1]
Is this project still being supported? Nothing appears to be imported when I add this as a Gradle dependency.

**Comment by dapacheco** [comment]
@troyjperales I found that you had to import it with the `@aar` annotation to get it to add the library.
`compile 'com.meetme.android:font-compat:1.0@aar'`

**Comment by troyjperales** [comment]
Worked. Thanks. Created #3.
